- type: playTimeTracker
  id: JobBlueshieldOfficer

- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobDSCommander

- type: playTimeTracker
  id: JobDSOfficer

- type: playTimeTracker
  id: JobDSSpecialist

- type: playTimeTracker
  id: JobSeniorEngineer

- type: playTimeTracker
  id: JobSeniorPhysician

- type: playTimeTracker
  id: JobSeniorResearcher

- type: playTimeTracker
  id: JobSeniorOfficer

